// SPDX-License-Identifier: Apache-2.0

import type { Metadata } from "next";
import { SolanaProvider } from './providers/WalletProvider';

import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { Bounce, ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Launch A Pool Wizard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
        <SolanaProvider>{children}</SolanaProvider>
      </body>
    </html>
  );
}
